# Generated by Django 5.0.6 on 2024-08-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_arabiclevel_contactsubmission_arabic_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
