# Generated by Django 5.0.6 on 2024-08-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_contactsubmission_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='message',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
