# Generated by Django 5.0.6 on 2024-08-30 21:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_contactsubmission_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^(\\+\\d{1,3}[- ]?)?(?=.{8,15}$)\\d+$', 'Enter a valid phone number with the following format +999999999')]),
        ),
    ]
