# Generated by Django 5.0.6 on 2024-07-17 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_delete_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
