# Generated by Django 5.0.6 on 2024-08-26 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactsubmission',
            old_name='arabicLevel',
            new_name='arabic_level',
        ),
        migrations.RenameField(
            model_name='contactsubmission',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='contactsubmission',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='contactsubmission',
            old_name='nativeLanguage',
            new_name='native_language',
        ),
        migrations.RenameField(
            model_name='contactsubmission',
            old_name='originCountry',
            new_name='origin_country',
        ),
    ]
