# Generated by Django 5.0.6 on 2024-08-29 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_contactsubmission_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Only letters are allowed in the last name.')]),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='message',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
