# Generated by Django 5.0.6 on 2024-08-30 20:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_contactsubmission_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='phone',
            field=models.CharField(error_messages={'max_length': 'Phone number cannot exceed 15 digits.'}, max_length=15, validators=[django.core.validators.RegexValidator('^(\\+\\d{1,3}[- ]?)?(?=.{10,15}$)\\d+$', 'Enter a valid phone number with the following format +999999999')]),
        ),
    ]
